# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tynchtyk/Desktop/ATM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tynchtyk/Desktop/ATM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tynchtyk/Desktop/ATM/CMakeFiles /home/tynchtyk/Desktop/ATM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tynchtyk/Desktop/ATM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

accounts/account.o: accounts/account.cc.o
.PHONY : accounts/account.o

# target to build an object file
accounts/account.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/accounts/account.cc.o
.PHONY : accounts/account.cc.o

accounts/account.i: accounts/account.cc.i
.PHONY : accounts/account.i

# target to preprocess a source file
accounts/account.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/accounts/account.cc.i
.PHONY : accounts/account.cc.i

accounts/account.s: accounts/account.cc.s
.PHONY : accounts/account.s

# target to generate assembly for a file
accounts/account.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/accounts/account.cc.s
.PHONY : accounts/account.cc.s

atm/atm.o: atm/atm.cc.o
.PHONY : atm/atm.o

# target to build an object file
atm/atm.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/atm/atm.cc.o
.PHONY : atm/atm.cc.o

atm/atm.i: atm/atm.cc.i
.PHONY : atm/atm.i

# target to preprocess a source file
atm/atm.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/atm/atm.cc.i
.PHONY : atm/atm.cc.i

atm/atm.s: atm/atm.cc.s
.PHONY : atm/atm.s

# target to generate assembly for a file
atm/atm.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/atm/atm.cc.s
.PHONY : atm/atm.cc.s

cards/card.o: cards/card.cc.o
.PHONY : cards/card.o

# target to build an object file
cards/card.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cards/card.cc.o
.PHONY : cards/card.cc.o

cards/card.i: cards/card.cc.i
.PHONY : cards/card.i

# target to preprocess a source file
cards/card.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cards/card.cc.i
.PHONY : cards/card.cc.i

cards/card.s: cards/card.cc.s
.PHONY : cards/card.s

# target to generate assembly for a file
cards/card.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cards/card.cc.s
.PHONY : cards/card.cc.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

states/account_selected_state.o: states/account_selected_state.cc.o
.PHONY : states/account_selected_state.o

# target to build an object file
states/account_selected_state.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/account_selected_state.cc.o
.PHONY : states/account_selected_state.cc.o

states/account_selected_state.i: states/account_selected_state.cc.i
.PHONY : states/account_selected_state.i

# target to preprocess a source file
states/account_selected_state.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/account_selected_state.cc.i
.PHONY : states/account_selected_state.cc.i

states/account_selected_state.s: states/account_selected_state.cc.s
.PHONY : states/account_selected_state.s

# target to generate assembly for a file
states/account_selected_state.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/account_selected_state.cc.s
.PHONY : states/account_selected_state.cc.s

states/card_inserted_state.o: states/card_inserted_state.cc.o
.PHONY : states/card_inserted_state.o

# target to build an object file
states/card_inserted_state.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/card_inserted_state.cc.o
.PHONY : states/card_inserted_state.cc.o

states/card_inserted_state.i: states/card_inserted_state.cc.i
.PHONY : states/card_inserted_state.i

# target to preprocess a source file
states/card_inserted_state.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/card_inserted_state.cc.i
.PHONY : states/card_inserted_state.cc.i

states/card_inserted_state.s: states/card_inserted_state.cc.s
.PHONY : states/card_inserted_state.s

# target to generate assembly for a file
states/card_inserted_state.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/card_inserted_state.cc.s
.PHONY : states/card_inserted_state.cc.s

states/no_card_state.o: states/no_card_state.cc.o
.PHONY : states/no_card_state.o

# target to build an object file
states/no_card_state.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/no_card_state.cc.o
.PHONY : states/no_card_state.cc.o

states/no_card_state.i: states/no_card_state.cc.i
.PHONY : states/no_card_state.i

# target to preprocess a source file
states/no_card_state.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/no_card_state.cc.i
.PHONY : states/no_card_state.cc.i

states/no_card_state.s: states/no_card_state.cc.s
.PHONY : states/no_card_state.s

# target to generate assembly for a file
states/no_card_state.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/no_card_state.cc.s
.PHONY : states/no_card_state.cc.s

states/pin_entered_state.o: states/pin_entered_state.cc.o
.PHONY : states/pin_entered_state.o

# target to build an object file
states/pin_entered_state.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/pin_entered_state.cc.o
.PHONY : states/pin_entered_state.cc.o

states/pin_entered_state.i: states/pin_entered_state.cc.i
.PHONY : states/pin_entered_state.i

# target to preprocess a source file
states/pin_entered_state.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/pin_entered_state.cc.i
.PHONY : states/pin_entered_state.cc.i

states/pin_entered_state.s: states/pin_entered_state.cc.s
.PHONY : states/pin_entered_state.s

# target to generate assembly for a file
states/pin_entered_state.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/states/pin_entered_state.cc.s
.PHONY : states/pin_entered_state.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... accounts/account.o"
	@echo "... accounts/account.i"
	@echo "... accounts/account.s"
	@echo "... atm/atm.o"
	@echo "... atm/atm.i"
	@echo "... atm/atm.s"
	@echo "... cards/card.o"
	@echo "... cards/card.i"
	@echo "... cards/card.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... states/account_selected_state.o"
	@echo "... states/account_selected_state.i"
	@echo "... states/account_selected_state.s"
	@echo "... states/card_inserted_state.o"
	@echo "... states/card_inserted_state.i"
	@echo "... states/card_inserted_state.s"
	@echo "... states/no_card_state.o"
	@echo "... states/no_card_state.i"
	@echo "... states/no_card_state.s"
	@echo "... states/pin_entered_state.o"
	@echo "... states/pin_entered_state.i"
	@echo "... states/pin_entered_state.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

